name = "runpod-registry"

main = "./index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

## Production
[env.production]
r2_buckets = [
  { binding = "REGISTRY", bucket_name = "runpod-registry" }
]

[env.development]
r2_buckets = [
  { binding = "REGISTRY", bucket_name = "runpod-registry" }
]

# Secrets:
# USERNAME/PASSWORD/READONLY_USERNAME/READONLY_PASSWORD if you want username/password based auth

[observability]
enabled = true
head_sampling_rate = 1